### ISSUE TITLE
Fix user popup info getting stuck open

### ISSUE THREAD

**Issue by madhatr** [carlbennett/BNRBot#13] opened 2015-09-27 00:04 UTC
The popup info in the channel user list window gets stuck open almost consistently.  It will also remain hovering when you switch to a different application.   It does close when you minimize the program.

Windows 10 x64 intel.

**Comment by carlbennett** [comment] 2015-09-27 00:07
Can you get me a snapshot? I think I know what you're talking about but I want to be sure.

You can Print-screen and paste into a comment here.

**Comment by madhatr** [comment] 2015-09-27 00:14
Here are two screen caps, one with the bot open and cursor moved out of channel user list window(which you can't see since print screen doesn't grab the cursor I guess.) and one while I was making the png you can see the popup still floating while I'm using paint.

![untitled](https://cloud.githubusercontent.com/assets/14855242/10120511/63c24100-6493-11e5-89e9-d5d216a1d152.png)
![untitled1](https://cloud.githubusercontent.com/assets/14855242/10120512/63c2c8fa-6493-11e5-93af-bd31d984917b.png)

**Comment by carlbennett** [comment] 2015-09-27 03:29
I can reproduce this error if I have my mouse hover over a user, alt+tab to a window that comes in front of the bot, and then start doing stuff outside the bot.

This won't be an easy fix since that help tip is displayed by the OS framework. I'll probably have to refactor using my own.

**Comment by madhatr** [comment] 2015-09-27 12:12
Can you reproduce the part where it gets stuck open while still in the bot window.  Mine stays until I pass the mouse through the channel user list enough times until it disappears the way I assume it is supposed to.

**Comment by carlbennett** [comment] 2015-09-27 20:27
I can't reproduce that. When the help tip appears, the mouse is on top of it. When I move the mouse outside of the help tip box, the box closes immediately. It only stays open if I alt+tab to another program that displays itself on top of the main window.

**Comment by madhatr** [comment] 2015-09-28 12:10
Maybe it is my OS.   Win 10 x64.    Unless you are on the same OS.  I'm not really sure what would cause it.   I was just messing around with it.  It is as though it is not catching the fact that my mouse has left the popup area.   I can get it to disappear if I stay hovering in the pop for a few extra seconds around the middle and than very slowly leave it via the top or bottom,  no luck left or right.

**Comment by carlbennett** [comment] 2015-09-29 03:38
I'm on Win 7 x64.

**Comment by carlbennett** [comment] 2016-04-19 06:03
Resolved in f99992fdcac9587886c9300e4df731adbf2b756f.

**Closed as completed by carlbennett** 2016-04-19 06:03 UTC
Labels: bug
